//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieTitle()
        {
            this.MovieActors = new HashSet<MovieActor>();
        }
    
        public int MovieID { get; set; }
        public string MovieTitle1 { get; set; }
        public int GenreID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int UnitsInStock { get; set; }
        public short ReleaseYear { get; set; }
        public int MovieRatingID { get; set; }
        public string Runtime { get; set; }
        public int DirectorID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> AspectRatioID { get; set; }
        public Nullable<bool> IsColor { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int StatusID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual AspectRatio AspectRatio { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual Director Director { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieActor> MovieActors { get; set; }
        public virtual MovieRating MovieRating { get; set; }
        public virtual MovieStatus MovieStatu { get; set; }
    }
}
